# Aula 02 - Python
## Dados Numéricos

In [1]:
# Variável inteira
a = 1
print('Valor de a = '+str(a))
type(a)

Valor de a = 1


int

In [2]:
# Variável dupla precisão
b = 1.0
print(b)
type(b)

1.0


float

In [3]:
# Converter float para int
c = int(b)
print(c)
type(c)

1


int

In [5]:
# Delacrando nan
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

In [6]:
# Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)

nan
nan
1.0


## Dados de Texto

In [7]:
# Declaração de variável texto
f = 'Fábio'
g = "Gabriel"
print(f)
print(g)
print(f+g)
print(f+' '+g)

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


## Dados tipo bool - lógica

In [8]:
a == 1

True

In [9]:
h = (a==1)
print(h)
type(h)

True


bool

In [10]:
h = (a==2)
print(h)
type(h)

False


bool

In [11]:
i = True
type(i)

bool

In [12]:
ii = 'True'
type(ii)

str

## Operação de comparação

In [13]:
# Operação ==
a==b

True

In [14]:
# Operação ><
a>b

False

In [15]:
# Operação !=
a!=b

False

In [16]:
# Operação >= ou <=
a>=b

True

## Operações matemáticas

In [17]:
# Soma 
a+b

2.0

In [18]:
# Soma e atribui valor
ab = a+b
print(ab)

2.0


In [19]:
# Multiplicação
l = a*b # Não use l como variável
print("Não use l como nome de variável")
j = a*b
print(j)

Não use l como nome de variável
1.0


In [20]:
# Divisão
a/b

1.0

In [21]:
# Potencia
5**2

25

In [22]:
# Operações matemáticas com a bibliotéca math
import math

math.exp(10)

22026.465794806718

In [23]:
math.exp(0)


1.0

In [24]:
math.exp(a)

2.718281828459045

In [25]:
math.exp(-10)

4.5399929762484854e-05

In [26]:
import math as mt
mt.log(c)

0.0

In [27]:
mt.log10(100)

2.0

## Listas

In [28]:
myFirstList = [1,2,3]
print(myFirstList)

[1, 2, 3]


In [29]:
# Acessando valores da lista pelo index
print(myFirstList[0])
print(myFirstList[2])

1
3


In [30]:
myFirstList==a

False

In [31]:
myFirstList[0]==a

True

In [32]:
mySecList = [1,a,'c']
print(mySecList)

[1, 1, 'c']


In [33]:
type(mySecList)

list

In [34]:
type(mySecList[2])

str

In [35]:
type(mySecList[1])

int

## Caminhos = path

In [41]:
path = r"C:\Users\mikae\Downloads\poluicao\GitHub\ENS5173_20241"
print(path)

C:\Users\mikae\Downloads\poluicao\GitHub\ENS5173_20241


In [47]:
path = "C:/Users/mikae/Downloads/poluicao/GitHub/ENS5173_20241"
print(path)

C:/Users/mikae/Downloads/poluicao/GitHub/ENS5173_20241


In [46]:
import os
# Listar arquivos na pasta
os.listdir(path)

['.git',
 '.gitignore',
 '.ipynb_checkpoints',
 'Aula01.ipynb',
 'imput',
 'scripts',
 'venv']

In [48]:
# Selecionar primeiro arquivo listado
os.listdir(path)[0]

'.git'

In [49]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0]

'C:/Users/mikae/Downloads/poluicao/GitHub/ENS5173_20241/.git'

In [50]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [51]:
# Diretório que estou trababalhando
os.getcwd()

'C:\\Users\\mikae\\Downloads\\poluicao\\GitHub\\ENS5173_20241\\venv\\Scripts'

In [52]:
# Mudo de diretório para o caminho 
os.chdir('C:\\Users\\mikae\\Downloads\\')

In [53]:
os.getcwd()

'C:\\Users\\mikae\\Downloads'

In [54]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

Criando diretório C:\Users\mikae\Downloads/test


In [55]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

Criando diretório C:\Users\mikae\Downloads/test2


## Numpy arrays e Pandas DataFrames

In [56]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)

numpy.ndarray

In [57]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)

[ 1  2  3 10 20 55]


In [58]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10)
print(n)
# Dimensões da matrix
print(n.shape)

[[0.52265641 0.02470011 0.51220528 0.63040369 0.57178722 0.40060452
  0.88638997 0.49599463 0.81976036 0.31047544]
 [0.99018222 0.67131072 0.72234504 0.68861798 0.90111132 0.74835897
  0.99115638 0.06091334 0.87904814 0.68906514]
 [0.26614308 0.93952419 0.5878983  0.10843012 0.28677541 0.08175595
  0.6736901  0.37542421 0.98411279 0.94582735]
 [0.58182284 0.67994103 0.8304158  0.35222969 0.56834961 0.71041475
  0.10103176 0.95861368 0.85105064 0.08720123]
 [0.07384829 0.27288488 0.12587519 0.83435499 0.63420261 0.57507406
  0.32116993 0.30276755 0.65324398 0.88450429]
 [0.32246238 0.85270908 0.61298845 0.47079814 0.65303431 0.66105337
  0.20417801 0.11159129 0.18276094 0.87521994]
 [0.83751982 0.81583003 0.92674062 0.24759414 0.77394069 0.54423249
  0.07992129 0.52500103 0.65598469 0.7531723 ]
 [0.73635813 0.88105576 0.17723757 0.68054955 0.35859143 0.35720293
  0.94477207 0.98390541 0.45261304 0.40168222]
 [0.86174836 0.5904072  0.55656226 0.08520336 0.47142832 0.16639765
  0.68465939

In [59]:
# Acessando valores da matriz
n[0,:]

array([0.52265641, 0.02470011, 0.51220528, 0.63040369, 0.57178722,
       0.40060452, 0.88638997, 0.49599463, 0.81976036, 0.31047544])

In [60]:
n[:,0]

array([0.52265641, 0.99018222, 0.26614308, 0.58182284, 0.07384829,
       0.32246238, 0.83751982, 0.73635813, 0.86174836, 0.51065449])

In [61]:
n[:,1:5]

array([[0.02470011, 0.51220528, 0.63040369, 0.57178722],
       [0.67131072, 0.72234504, 0.68861798, 0.90111132],
       [0.93952419, 0.5878983 , 0.10843012, 0.28677541],
       [0.67994103, 0.8304158 , 0.35222969, 0.56834961],
       [0.27288488, 0.12587519, 0.83435499, 0.63420261],
       [0.85270908, 0.61298845, 0.47079814, 0.65303431],
       [0.81583003, 0.92674062, 0.24759414, 0.77394069],
       [0.88105576, 0.17723757, 0.68054955, 0.35859143],
       [0.5904072 , 0.55656226, 0.08520336, 0.47142832],
       [0.3548773 , 0.75510682, 0.5722331 , 0.56845851]])

In [63]:
n[0,1:5]

array([0.02470011, 0.51220528, 0.63040369, 0.57178722])

In [64]:
n[0,-1]

0.3104754406698075

In [65]:
n[0,4:-1]

array([0.57178722, 0.40060452, 0.88638997, 0.49599463, 0.81976036])

In [66]:
n[0,4:]

array([0.57178722, 0.40060452, 0.88638997, 0.49599463, 0.81976036,
       0.31047544])

In [67]:
an = np.log(n*5)
print(an)

[[ 0.96060692 -2.09150985  0.94040811  1.14804303  1.05044957  0.69465733
   1.48883963  0.90824774  1.41069469  0.43978744]
 [ 1.59957162  1.21091473  1.28418556  1.2363693   1.50531144  1.3195654
   1.60055496 -1.18886514  1.4805223   1.23701845]
 [ 0.2857167   1.5470562   1.07823661 -0.6122115   0.36038201 -0.89457877
   1.21445285  0.62973924  1.59342315  1.55374268]
 [ 1.06784863  1.22368871  1.42360918  0.56596613  1.04441937  1.26753159
  -0.68288241  1.56717079  1.44815427 -0.83009897]
 [-0.99630452  0.31073267 -0.4630265   1.42834159  1.15405112  1.05618146
   0.47365299  0.41464798  1.18363333  1.48670999]
 [ 0.47766911  1.45010106  1.12002873  0.85611206  1.18331231  1.19551721
   0.02067485 -0.58347434 -0.09013842  1.47615785]
 [ 1.43212756  1.40588867  1.53335636  0.21347352  1.35317787  1.00105916
  -0.91727504  0.96508285  1.18782009  1.32597665]
 [ 1.30339922  1.48280355 -0.12082635  1.22458327  0.58386629  0.57998668
   1.55262633  1.5932124   0.81672018  0.69734391]
 